[package]
name = "fizzle"
description = "carbonate your shell"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.100"
smol = "2.0.2"
rand = "0.9.2"
futures = "0.3.31"
portable-pty = "0.9.0"

[dependencies.anathema]
version = "0.2.11"
