[package]
name = "canvas-effects"
version = "0.1.0"
authors = ["kikiala"]
edition = "2024"

[dependencies]
rand = "0.9.2"

[dependencies.anathema]
version = "0.2.11"
# git = "https://github.com/togglebyte/anathema.git"
